name: check

on:
  push:
    branches: ["[0-9]+.x", main, rc, beta, alpha]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.5,just@1,cargo-msrv@0.15,cargo-deny@0.13,nu@0.76
      - run: just verify
      - run: cargo build --release
      - run: nu -c "register target/release/nu_plugin_from_beancount; open src/example.beancount"
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,just,cargo-deny,nu
      - run: just lint
      - run: cargo deny check
